name: Docker Image CI
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image of python flaskapp
      run: docker build . --file Dockerfile-app --tag dilipkumarashok/flaskapp:$(date +%s)
    - name: Build the Docker image of mysql
      run: docker build . --file Dockerfile-mysql --tag dilipkumarashok/mysqldb:$(date +%s)